# Generated by Django 5.1.6 on 2025-03-20 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_projects', to=settings.AUTH_USER_MODEL)),
                ('employees', models.ManyToManyField(related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Detail',
            fields=[
                ('project_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('save_date', models.DateField(auto_now_add=True)),
                ('image', models.BinaryField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='designer.project')),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('window_id', models.AutoField(primary_key=True, serialize=False)),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('project_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='designer.project_detail')),
            ],
        ),
    ]
