# Generated by Django 5.1.6 on 2025-04-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
