# Generated by Django 5.1.6 on 2025-04-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_alter_project_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
