# Generated by Django 5.1.6 on 2025-04-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_preview_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
