# Generated by Django 5.1.6 on 2025-04-09 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_projectstatus_notes_alter_projectstatus_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('frame_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.BinaryField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='window',
            name='frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='designer.frame'),
        ),
    ]
