# Generated by Django 5.1.6 on 2025-04-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_projectstatus_planned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='project',
            name='order_number',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
