# Generated by Django 5.1.6 on 2025-04-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_frame_window_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
