# Generated by Django 5.1.6 on 2025-04-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0006_alter_customer_first_name_alter_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='x1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='window',
            name='x2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='window',
            name='y1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='window',
            name='y2',
            field=models.FloatField(),
        ),
    ]
