# Generated by Django 5.1.6 on 2025-04-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0007_alter_window_x1_alter_window_x2_alter_window_y1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='x1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='window',
            name='x2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='window',
            name='y1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='window',
            name='y2',
            field=models.IntegerField(),
        ),
    ]
